version: "3.9"

services:
  web:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/procentapi
    env_file:
      - ./.env
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis
      - rabbitmq
      - celery
  db:
    image: postgres:16

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"

  celery:
    build: .
    command: celery -A procentapi worker -l info
    volumes:
      - .:/code
    env_file:
      - ./.env
    depends_on:
      - redis
